### ISSUE TITLE
error on decrypt process

### ISSUE THREAD

**Issue by ysrc26** [tweksteen/jenkins-decrypt#1]
hey bro,  i got error during decrypt hudson.secret.key:

Traceback (most recent call last):
  File "C:\decryptor\decrypt.py", line 50, in <module>
    main()
  File "C:\decryptor\decrypt.py", line 33, in main
    x = o.decrypt(hudson_secret_key)
  File "build\bdist.win32\egg\Crypto\Cipher\blockalgo.py", line 295, in decrypt
ValueError: Input strings must be a multiple of 16 in length

thanks for help!
![error](https://cloud.githubusercontent.com/assets/5815227/10310865/cd267380-6c4c-11e5-90a4-105e0a2e38bc.png)

**Comment by tweksteen** [comment]
Hey,

It seems like you have the wrong size for the file hudson.util.Secret. Could you confirm it is 272 bytes long?
Otherwise, the format may have changed since I wrote that script. Feel free to follow thiébaud.fr/jenkins_credentials.html, you may notice some difference with your version.

Oh, and please: http://imgur.com/ybsOOsX

**Comment by ysrc26** [comment]
hey,
yes it's 272 bytes.
![error_2](https://cloud.githubusercontent.com/assets/5815227/10448145/6ae11fda-7193-11e5-8657-529b1949a1ee.png)

and sorry about bro :)

**Comment by tweksteen** [comment]
Hum... have you modified the script? Because line 33 (where the error is triggered) should be 'for password in passwords:' and not that decrypt call.

Could you add a 'print  hexlify(hudson_secret_key)' just before the decrypt call to see the exact value used?

Also, your credentials.xml should contains a <password> tag (with a lower case). I do think you are using a different format that may not be compatible with the version I tested. Did you edit the credentials.xml by hand?

**Comment by ysrc26** [comment]
hi,
i changed the script just with some print commands.
i'm attaching the output of 'print hexlify(hudson_secret_key) as you suggested.
and credentials.xml, decrypt.py files
![credentials xml](https://cloud.githubusercontent.com/assets/5815227/10482597/f1bc9a72-7281-11e5-9d4d-f4d04ed3b83a.png)
![decryptor py](https://cloud.githubusercontent.com/assets/5815227/10482599/f1be9db8-7281-11e5-8c0f-0acdcd8ca196.png)
![print hexlify hudsin util secret](https://cloud.githubusercontent.com/assets/5815227/10482598/f1bcddac-7281-11e5-835c-d7e1b3ab10a0.png)

**Comment by tweksteen** [comment]
Ah I think I know, the Python file handling on Windows requires a special flag for binary files. Try to replace the 

```
hudson_secret_key = open(sys.argv[2]).read()
```

with

```
hudson_secret_key = open(sys.argv[2], 'rb').read()
```

If that works, could you patch your fork and send a pull request? Thanks

**Comment by ysrc26** [comment]
well, it's working now,
thanks!
